---
version: "3"
services:
 devopsdb:
   image: suneeldevops8688/mynewapp:dbimage
   ports:
     - "2222:3306"

 application:
   image: suneeldevops8688/mynewapp:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
