---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/valluri:dbimage
   ports:
     - "2222:3306"

 application:
   image: shaikmustafa/valluri:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
